### ISSUE TITLE
Unable to compile Java files

### ISSUE THREAD

**Issue by giok1992** [joelmo/pine-js#2]
hello,

I'm trying to compile this but running into issues. After processing the grammar file, I try to build it but run into these errors:

`SpineLexer.java:104: error: illegal start of expression
	SpineLexer.prototype.indents = [0];
	                               ^
SpineLexer.java:106: error: illegal start of expression
	SpineLexer.prototype.token_queue = [];
	                                   ^
SpineLexer.java:108: error: ';' expected
	SpineLexer.prototype.nextToken = function() {
	                                           ^
SpineLexer.java:113: error: ';' expected
	SpineLexer.prototype.pushToken = function(type, text) {
	                                                     ^
SpineLexer.java:121: error: ';' expected
	SpineLexer.prototype.previous = function() {
	                                          ^
SpineLexer.java:161: error: illegal start of expression
			let spaces = this.text.replace(/[\r\n]+/g, '');
			                               ^
SpineLexer.java:161: error: illegal start of expression
			let spaces = this.text.replace(/[\r\n]+/g, '');
			                                ^
SpineLexer.java:161: error: illegal character: '\'
			let spaces = this.text.replace(/[\r\n]+/g, '');
			                                 ^
SpineLexer.java:161: error: illegal character: '\'
			let spaces = this.text.replace(/[\r\n]+/g, '');
			                                   ^
SpineLexer.java:161: error: not a statement
			let spaces = this.text.replace(/[\r\n]+/g, '');
			                                  ^
SpineLexer.java:161: error: not a statement
			let spaces = this.text.replace(/[\r\n]+/g, '');
			                                    ^
SpineLexer.java:161: error: ';' expected
			let spaces = this.text.replace(/[\r\n]+/g, '');
			                                     ^
SpineLexer.java:161: error: not a statement
			let spaces = this.text.replace(/[\r\n]+/g, '');
			                                        ^
SpineLexer.java:161: error: ';' expected
			let spaces = this.text.replace(/[\r\n]+/g, '');
			                                         ^
SpineLexer.java:161: error: empty character literal
			let spaces = this.text.replace(/[\r\n]+/g, '');
`

Thanks

**Comment by joelmo** [comment]
I don't see what your build target is but the parser is written for
JavaScript.
